name: Draft Release

on:
  pull_request:
    types: [closed]

jobs:
  draft_release:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      contains(github.event.pull_request.title, 'chore(release)')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read package.json
        id: read-package-json
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get merged commit hash
        id: get-merge-commit
        run: |
          echo "MERGED_COMMIT=${{ github.event.pull_request.merge_commit_sha }}" >> $GITHUB_ENV

      - name: Create Draft Release
        run: |
          version="${{ steps.read-package-json.outputs.version }}" # Assuming you have the version available as an output from a previous step
          merged_commit="${{ env.MERGED_COMMIT }}"

          # Create the release with the merged commit's hash as the reference
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "v'"$version"'",
              "name": "Release v'"$version"'",
              "body": "Release targeting commit hash: '"$merged_commit"'",
              "draft": true,
              "target_commitish": "'"$merged_commit"'"
            }')

          release_url=$(echo "$response" | jq -r '.html_url')

          if [ -z "$release_url" ]; then
            echo "Error creating draft release"
            exit 1
          else
            echo "Draft release created: $release_url"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
